config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_one_attached :picture

  validates_presence_of     :name
  validates_presence_of     :address
  validates :phone,:presence => true, :numericality => true, :length => { :minimum => 10, :maximum => 15 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?
    
    protected
    	def configure_permitted_parameters
	    	devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :address, :phone,:picture])
	    	devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :password, :address, :phone,:picture])
	  	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	
	def index
		if current_user && current_user.isadmin?
			@user=User.where(isadmin: false)
		end	
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected
  def update_resource(resource, params)
    resource.update_without_password(params)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def edit
     @user = User.find(params[:id])
   end
   def update
     @user = User.find(params[:id])
     if @user.update(user_params)
       redirect_to root_path
     else
       redirect_to root_path
     end
   end
   private
  
  def user_params
    params.require(:user).permit(:name, :email, :address, :phone,:picture)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<p class="navbar-text float-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% if current_user.isadmin?%>
  <table>
  <tr>
    <th>Image</th>
    <th>Name</th>
    <th>Phone</th>
    <th>Address</th>
    <th>Action</th>
  </tr>
  <% @user.each do |userdetail| %>
	<tr>
	    <td><%= image_tag url_for(userdetail.picture), :style=>"width: 40px; height: 40px;"  if userdetail.picture.attached? %></td>
	    <td><%= userdetail.name %></td>
	    <td><%= userdetail.phone %></td>
	    <td><%= userdetail.address %></td>
	    <td><%= link_to "Edit", edit_user_path(userdetail) %></td>
	</tr>
  <%end%>
</table>
  <%end%>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rubydemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<%= form_for(@user) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: true, :disabled => true %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address , :disabled => @user.isadmin==true %>
  </div> 
  <%= image_tag url_for(@user.picture)  if @user.picture.attached? %>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone, :disabled =>  @user.isadmin!=true %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, :disabled => true %>
  </div>

  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>
<%= link_to "Back", :back %>